CREATE TABLESPACE NewCanalPanamaTS DATAFILE 'C:\temporal\NewCanalPanamaTS.DBF' SIZE 1024M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TEMPORARY TABLESPACE NewCanalPanamaTemp TEMPFILE 'C:\temporal\NewCanalPanamaTemp.DBF' SIZE 300M;

CREATE USER CanalPanamaUsr IDENTIFIED BY panamaUD DEFAULT TABLESPACE NewCanalPanamaTS TEMPORARY TABLESPACE NewCanalPanamaTemp;

GRANT dba, connect, resource TO CanalPanamaUsr;

