----- TRIGGER AUDITORÍA RESERVA
CREATE OR REPLACE TRIGGER TG_AUDITORIA_RESERVA
AFTER UPDATE OF I_ESTADO ON RESERVA
FOR EACH ROW
BEGIN
    UPDATE RESERVA
       SET f_fecha_modifica_estado = SYSDATE,
           n_usuario_modifica_estado = user
     WHERE k_reserva = :OLD.K_RESERVA;
    DBMS_OUTPUT.put_line('Ejecutó TRIGGER de Auditoría');
END TG_AUDITORIA_RESERVA;


----- TRIGGER AUDITORIA TARIFA

CREATE OR REPLACE TRIGGER TG_AUDITORIA_TARIFA
AFTER UPDATE OF K_TARIFA ON TARIFA
FOR EACH ROW
BEGIN
    UPDATE TARIFA
       SET F_FECHA_MODIFICA = SYSDATE,
           N_USUARIO_MODIFICA = user
     WHERE k_reserva = :OLD.K_TARIFA;
    DBMS_OUTPUT.put_line('Ejecutó TRIGGER de TARIFA');
END TG_AUDITORIA_RESERVA;